# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sanjay Nair
tagline:             'Personal Website'
description:         'Software Engineer. Atlanta, Georgia, USA'
url:                 http://nirespire.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sanjay Nair
  url:               https://twitter.com/nirespire
  email:             

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
